<?php
#
# Murmur.php is generated by calling
# slice2php /path/to/Murmur.ice
# in this directory
#


if (!isset($_SERVER['PHP_AUTH_USER']) || $_SERVER['PHP_AUTH_USER'] != "test" || $_SERVER['PHP_AUTH_PW'] != "test") {
    header('WWW-Authenticate: Basic realm="MumbleHost"');
    header('HTTP/1.0 401 Unauthorized');
    echo 'Invalid User!';
    exit;
}


if (Ice_intversion() >= 30400) {
	if (!stream_resolve_include_path('Ice.php')) {
		exit('The required file Ice.php could not be found in the PHP include path(s).');
	}
	if (!stream_resolve_include_path('Murmur.php')) {
		exit('The required file Murmur.php could not be found in the PHP include path(s).');
	}
	require 'portFunctions.php';
	require 'Ice.php';
	require 'Murmur.php';
} else {
	Ice_loadProfile();
}
	$contentMain = 
		"";

	$ports = getAvailablePorts();


	$inputs .= "<div class=\"input-group\">";
	$inputs .= "<span class=\"input-group-addon\">Titel</span>";
	$inputs .= "<input type=\"text\" class=\"form-control\" name=\"config[registername]\" value=\"".$name."\"/>";
	$inputs .= "</div>";

	$inputs .= "<div class=\"input-group\">";

	$inputs .= "<input type=\"hidden\" class=\"form-control\" name=\"config[port]\" value=\"".$ports[0][0]."\">";

	$inputs .= "</div>";

	$inputs .= "<div class=\"input-group\">";
	$inputs .= "<span class=\"input-group-addon\">Server Passwort</span>";
	$inputs .= "<input type=\"text\" class=\"form-control\" name=\"config[serverpassword]\" value=\"".$name."\"/>";
	$inputs .= "</div>";


	

$content = "<form action=\"control.php\" method=\"get\">
    <input type=\"hidden\" name=\"action\" value=\"new\" />";
$content .= "<input type=\"hidden\" name=\"id\" value=\"\" />";

$content .= $inputs;

$content .= 
  "</td></tr><tr><td><input type=\"submit\" class=\"btn btn-primary\" value=\"Speichern\"/>
    <input type=\"reset\" class=\"btn btn-warning\" value=\"Abbrechen\"/>
    </form>";

$templateMain = file_get_contents("./template/main.thtml");
$templateMain = str_replace("{{title}}", "Neuen Server anlegen", $templateMain);
$templateMain = str_replace("{{content}}", $content, $templateMain);
echo $templateMain;

?>
